version: '3.9'
services:
#  banners:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - '8892:8080'
#    depends_on:
#      - postgres
#      - redis
#      - jaeger
#    container_name: banners
#    networks:
#      - banners
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=test"
      - "POSTGRES_DB=avito"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54325:5432"
    networks:
      - banners
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6333:6379"
    networks:
      - banners
  jaeger:
    image: "jaegertracing/all-in-one:1.52"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778 # 405
      - 16686:16686 # ui
      - 14250:14250 # gRPC
      - 14268:14268 # 404
      - 14269:14269
      - 4317:4317 # otlp REST
      - 4318:4318 # otlp gRPC
      - 9411:9411 # 404
    networks:
      - banners

volumes:
  postgres_data:

networks:
  banners:
    name: banners
    external: true
